"""Task persistence boundary."""

from typing import Protocol

from app.modules.tasks.models_ds import Task, TaskEvent


class TaskStore(Protocol):
    def get(self, task_id: str) -> Task | None: ...

    def find_idempotent(
        self, actor_id: str, operation: str, resource_id: str, key: str
    ) -> Task | None: ...

    def create(self, task: Task) -> None: ...

    def claim(self, task_id: str) -> Task | None: ...

    def claim_recovery(self, task_id: str) -> Task | None: ...

    def reconcile_succeeded(
        self, task_id: str, detail: dict[str, object] | None = None
    ) -> Task: ...

    def update(self, task: Task) -> None: ...

    def append_event(self, event: TaskEvent) -> None: ...

    def append_next_event(
        self, task: Task, event_type: str, detail: dict[str, object] | None = None
    ) -> TaskEvent: ...

    def list_events(self, task_id: str) -> list[TaskEvent]: ...

    def latest_event(self, task_id: str, event_type: str) -> TaskEvent | None: ...

    def list_by_status(self, status: str) -> list[Task]: ...

    def list_by_operation_statuses(
        self, operation: str, statuses: tuple[str, ...]
    ) -> list[Task]: ...
