/**
 * API Client — re-exports.
 */
export type { ProblemDetails } from "./problem_ds.js";
export { isProblemDetails } from "./problem_ds.js";
export {
  MasterDataApi,
  type CreateMasterDataInput,
  type MasterDataAudit,
  type MasterDataCatalog,
  type MasterDataRecord,
  type UpdateMasterDataInput,
} from "./master-data_ds.js";
export {
  TemplateApi,
  type FillPolicy,
  type PaperEntryMode,
  type PreflightReport,
  type RecognitionMode,
  type TemplateArtifact,
  type TemplateDraftSummary,
  type TemplateElementKind,
  type TemplateField,
  type TemplateFieldInput,
  type TemplateLibraryItem,
  type TemplatePage,
  type TemplatePageInput,
  type TemplatePrintImposition,
  type TemplateRect,
  type TemplateStaticElement,
  type TemplateStatus,
  type TemplateVersion,
  isEditableTemplateStatus,
} from "./templates_ds.js";
export {
  ApiRequestError,
  ReviewWorkbenchApi,
  type AuditEvent,
  type ClassificationOption,
  type ConfirmAndClaimNextResult,
  type EvidenceItem,
  type FormSummary,
  type RecognitionCandidate,
  type RecordVersion,
  type ReviewField,
  type ReviewGroup,
  type ReviewFieldRules,
  type ReviewRuleFailure,
  type ReviewDraft,
  type ReviewHistory,
  type ReviewLease,
  type WorkbenchDetail,
} from "./review-workbench.js";
export {
  ExportApi,
  type CreateExportInput,
  type CreateExportResponse,
  type ExportApiRequestDefaults,
  type ExportBatch,
  type ExportExclusionReason,
  type ExportFilters,
  type ExportMapping,
  type ExportPreview,
  type ExportPreviewItem,
  type ExportReviewStatus,
  type ExportStatus,
  type ExportTask,
  type ExportTaskStatus,
  type IncludedExportRecord,
  type ReportDefinition,
  type ReportAssistantInput,
  type ReportAssistantResult,
  type ReportDefinitionStatus,
  type ReportKind,
  type AggregateOperation,
  type WaitForExportTaskOptions,
} from "./exports_ds.js";
export {
  TaskApi,
  type TaskStatusDetail,
} from "./tasks_ds.js";
export {
  ImportApi,
  type ImportBatchItem,
  type ImportBatchSummary,
  type ImportedImageSummary,
  type ImportItemStatus,
  type UploadImageResult,
} from "./imports_ds.js";
export {
  MobileApiClient,
  MobileApiError,
  mobileApiClient,
  type BambooDashboard,
  type BambooDailyBatch,
  type BambooEvidence,
  type BambooFinanceItem,
  type BambooFactoryEmployee,
  type BambooFormType,
  type BambooHistoryItem,
  type BambooInspection,
  type BambooOperationsSummary,
  type BambooPayrollFact,
  type BambooRecord,
  type BambooRecordPresetOptions,
  type BambooRoleChange,
  type BambooRoleOption,
  type BambooSourceSnapshot,
  type BambooStage,
  type BambooStageSubmission,
  type BambooTaskBucket,
  type MobileActiveResource,
  type MobileAvailableForm,
  type MobileContext,
  type MobileFetcher,
  type MobileFormField,
  type MobileFormSchema,
  type MobileLoginResponse,
  type MobileOption,
  type MobileProblem,
  type MobileProductionContext,
  type MobileSession,
  type MobileSubmissionInput,
  type MobileSubmissionListItem,
  type MobileSubmissionReceipt,
  type MobileTeamMember,
  type SubmitBambooStageInput,
} from "./mobile_ds.js";

// When generated types exist, uncomment:
// export type * from "./generated_ds.js";
