/**
 * Problem Details for HTTP APIs (RFC 9457 / RFC 7807).
 *
 * Mirrors the backend type at app.api.errors.problem_ds.ProblemDetails.
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type: string;

  /** A short, human-readable summary of the problem type. */
  title: string;

  /** The HTTP status code generated by the origin server. */
  status: number;

  /** A human-readable explanation specific to this occurrence. */
  detail: string;

  /** A URI reference that identifies the specific occurrence. */
  instance?: string;

  /** Additional diagnostic properties (extension members). */
  [key: string]: unknown;
}

/**
 * Type guard: returns true if `value` conforms to ProblemDetails shape.
 */
export function isProblemDetails(value: unknown): value is ProblemDetails {
  if (typeof value !== "object" || value === null) return false;
  const pd = value as Record<string, unknown>;
  return (
    typeof pd.type === "string" &&
    typeof pd.title === "string" &&
    typeof pd.status === "number" &&
    typeof pd.detail === "string"
  );
}
